# Fichier de configuration Python pour CircleCI 2.0
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9

    working_directory: ~/repo

    steps:
      # Étape 1 : Obtenir le référentiel de GitHub
      - checkout

      # Étape 2 : Créer un environnement virtuel et installer des dépendances
      - run:
          name: Installer les dépendances
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      # Étape 3 : Exécuter linter et tests
      - run:
          name: Exécuter linter et tests
          command: |
            . venv/bin/activate
            flake8 --exclude=venv* --statistics
            pytest -v --cov=calculator
